name: Bug 报告
description: 报告一个问题以帮助我们改进
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交 Bug 报告！请填写以下信息来帮助我们更好地定位和解决问题。

  - type: textarea
    id: bug-description
    attributes:
      label: Bug 描述
      description: 清晰简洁地描述遇到的问题
      placeholder: 描述您遇到的问题...
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: 描述如何重现这个问题
      placeholder: |
        1. 转到 '...'
        2. 点击 '...'
        3. 滚动到 '...'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 描述您期望发生的情况
      placeholder: 描述期望的行为...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果适用，请添加截图来帮助解释问题

  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 请提供相关的环境信息
      placeholder: |
        - OS: [例如 Windows 10, macOS 12.0]
        - 浏览器: [例如 Chrome 94, Safari 15]
        - Node.js版本: [例如 16.14.0]
        - 项目版本: [例如 v1.0.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加任何其他有关问题的上下文信息
